### ISSUE TITLE
Why to override layoutSubviews method in SlideLeafCell

### ISSUE THREAD

**Issue by Stmol** [horitaku46/Serrata#2]
https://github.com/horitaku46/Serrata/blob/88c2d5fadf1e1eb745f407b8232b33c89931d107/Serrata/Sources/SlideLeafCell.swift#L78

@horitaku46 in what case do you think we need to refresh subviews of the `SlideLeafCell`?
```
if let image = imageView.image {
       scrollView.setZoomScale(1, animated: false)
       calcImageViewFrame(image)
}
```

I found the case when it is called after double tap and the imageView inside `SlideLeafCell` is redrawn:
https://imgur.com/a/Ej3d4

In the video you can see that `layoutSubviews()` is called after I used `setNeedsStatusBarAppearanceUpdate()` and instead of to zoom, imageView is redrawn.

**Comment by horitaku46** [comment]
Hi! @Stmol .
Sorry for the late reply.
The reason why the following is described, if you zoom in on the image, rotate the iPhone and recalculate it, the display will collapse.
```swift
if let image = imageView.image {
       scrollView.setZoomScale(1, animated: false)
       calcImageViewFrame(image)
}
```

**Comment by Stmol** [comment]
thank you very much 👍
